config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'
  resources :photos do 
  	post 'publish', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup' => 'users#new'
  get 'login' => 'users#login'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
require 'mini_magick'
class Photo < ApplicationRecord
  has_one_attached :image
  enum status: [:draft,:published]
  belongs_to :user 
  validate :image_validation
  # validate :image_dimensions

  MAX_IMAGE_HEIGHT=200
  MAX_IMAGE_WIDTH=200

  def image_validation
  	if image.attached?
      if image.blob.byte_size > 2000000
        errors[:base] << 'Allowed size is 2MB'
      end
      if !image.blob.content_type.starts_with?('image/')
        errors[:base] << 'Format not allowed'
      end
    end
  end

  def publish_photo
  	published_at = Time.now 
  	status = :published
  	save
  end

 #  def image_dimensions 
 #  	if image.attached?
	#   	org_image= MiniMagick::Image.open(image.path)
	# 	if org_image.height > MAX_IMAGE_HEIGHT  ||
	# 	  org_image.width >MAX_IMAGE_WIDTH
	# 	  errors[:base] << 'Exceeds allowed dimensions'
	# 	  clean_file_path(org_image.path)
	# 	end
	# end
 #  end


  private 

  def clean_image_from_path(path)
  	File.delete(path)
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :username, :password, presence: true
	validates :username, uniqueness: true
	has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 # before_action :authenticate

	def logged_in?
    	!!@current_user
  	end

  	def authorize_request
    	header = session[:user_id]
    	begin
      		@decoded = Auth.decode(header)
      		@current_user = User.find(@decoded["user"])
      		params[:current_user] = @current_user.id
    	rescue ActiveRecord::RecordNotFound => e
      		render json: { errors: e.message }, status: :unauthorized
    	rescue JWT::DecodeError => e
      		redirect_to login_path
    	end
  	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :publish]
  before_action :authorize_request
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    @photos = @photos.where(user_id: params[:user]) if params[:user]
    if params[:filter] == 'My Photos'
      @photos = @photos.where(user_id: @current_user.id) 
    elsif params[:filter] == 'Draft'
      @photos = @photos.where(status: :draft)
    end
    if ['Desc','Asc'].include? params[:sort]
      @photos = Photo.where(status: :published).order("published_at #{params[:sort].downcase}")
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params.merge(user: @current_user))
    set_status(params)  
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    set_status(params) 
    respond_to do |format|
      updated = photo_params ? @photo.update(photo_params) : @photo.save
      if updated
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish 
    respond_to do |format|
    if @photo.publish_photo
      format.html { redirect_to @photo, notice: 'Photo was successfully published.' }
      format.json { render :show, status: :ok, location: @photo }
    else
      format.html { render :edit }
      format.json { render json: @photo.errors, status: :unprocessable_entity }
    end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :image) if params[:photo].present?
    end

    def set_status(params)
      if params[:commit] == 'Publish'
        @photo.published_at = Time.now
        @photo.status = :published
      else 
        @photo.published_at = nil 
        @photo.status = :draft
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		user = User.find_by(username: user_params[:username])
		unless user
      		user = User.create(user_params)
      		jwt = Auth.issue({user: user.id})
      		redirect_to photos_path, locals: { token: jwt }
      	else 
      		if user && user.authenticate(user_params[:password])
				jwt = Auth.issue({user: user.id})
				session[:user_id] = jwt
				redirect_to photos_path, locals: { token: jwt }

      		else 
      			flash[:message] = "Invalid user name/password"
      			redirect_to login_path
      		end
      	end
	end

	def login
		render 'login.html.erb'
	end



	private 
	def user_params 
		params.require(:user).permit(:username , :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <br>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption,  :maxlength => 100, :size => 70, :required=>true %>
  </div>
  <% unless params[:action] == 'edit'%>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image, required: true %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit 'Save as Draft' %>
  </div>
  <div class="actions">
    <%= form.submit 'Publish' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>
<%= form_tag(photos_path, :method => "get") do %>
  <%= select_tag 'filter', options_for_select([ "All", "My Photos", 'Draft' ], params[:filter] || 'All'), onchange: "this.form.submit();" %>
  <%= select_tag 'sort', options_for_select(['', "Desc", "Asc"], params[:sort] || ''), onchange: "this.form.submit();" %>
  <%= select_tag 'user', options_for_select(User.all.map{|u| [u.username, u.id]}), onchange: "this.form.submit();" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th>Image</th>
      <th> User </th>
      <th> Status </th>
      <th> Actions </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% hidden_field_tag 'token', @token %>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.caption %></td>
        <% if photo.image.attached? %>
          <td><image src="<%=(url_for(photo.image))%>"></td>
        <% end%>
        <td><%= photo.user.username %></td>
        <td><%= photo.status %></td>
        <td><%= link_to 'Show', photo %></td>
         <td><%= link_to 'Edit', edit_photo_path(photo) %> </td>
        <td><%= button_to 'Publish', publish_photo_path(photo), method: :post, remote: true, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<p>
  <strong>Image:</strong>
  <% if @photo.image.attached? %>
  	<image src="<%=(url_for(@photo.image))%>"> 
  <% end %>
</p>
<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/users/login.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :username %>
  <br><br>
  Password: <%= f.password_field :password %>
  <br><br>
 
  <%= f.submit "Submit" %>

<% end %>
<br>
<%= link_to('Sign up',signup_path) %>

app/views/users/new.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :username %>
  <br><br>
  Password: <%= f.password_field :password %>
  <br><br>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit "Submit" %>

<% end %>